Fix plist issues
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: include/node/openssl/archs/linux64-mips64/asm_avx2/crypto/buildinf.h
Error: Orphaned: include/node/openssl/archs/linux64-mips64/asm_avx2/crypto/include/internal/bn_conf.h
Error: Orphaned: include/node/openssl/archs/linux64-mips64/asm_avx2/crypto/include/internal/dso_conf.h
Error: Orphaned: include/node/openssl/archs/linux64-mips64/asm_avx2/include/openssl/opensslconf.h
Error: Orphaned: include/node/openssl/archs/linux64-mips64/asm_avx2/include/progs.h